# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-24 15:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitorcreator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='company_to_visit',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='visitor',
            name='employee_to_visit',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='visitor',
            name='mail_list_sub',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='photo',
            field=models.ImageField(blank=True, upload_to=b''),
        ),
    ]
